## R1704 (redefined-argument-from-local)

### :x: Problematic code:

```python
def greet_person(name, friends) -> None:
    """Print the name of a person and all their friends."""
    print("My name is {}".format(name))
    for name in friends:  # Error on this line
        print("I am friends with {}".format(name))
```

### :heavy_check_mark: Correct code:

```python
def greet_person(name, friends) -> None:
    """Print the name of a person and all their friends."""
    print("My name is {}".format(name))
    for friend in friends:
        print("I am friends with {}".format(friend))
```

### Rationale:

Used when a local name is redefining an argument, which might suggest a
potential error. This is taken in account only for a handful of name binding
operations, such as for iteration, with statement assignment and exception
handler assignment.

### Related resources:

- [Issue Tracker](https://github.com/PyCQA/pylint/issues?q=is%3Aissue+%22redefined-argument-from-local%22+OR+%22R1704%22)
